# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Cycle
version:      0.03
version_from: lib/Template/Plugin/Cycle.pm
installdirs:  site
requires:
    File::Spec:                    0.82
    Template:                      2.10
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
